const fs = require('fs');
const p = 'C:\\Users\\markj\\Desktop\\Claude-Projects\\Done Claude Ai Dental Websites\\calgary-south-dental-ai-website\\.tasks\\clone-royalbaydentalco\\context.md';

const lines = [
  '# Royal Bay Dental Co. — Clone Reference',
  '',
  '**Source URL**: https://royalbaydentalco.ca/',
  '**Captured**: 2026-05-10',
  '**Platform**: WordPress + Cornerstone/X Theme page builder (.x-section elements)',
  '',
  '---',
  '',
  '## Site Overview',
  '',
  'Single-page homepage for a Victoria, BC dental practice. Warm neutral palette (greige/tan, off-white, dark charcoal text). Elegant serif + clean sans-serif typography. Distinctive rotating vertical text labels (e.g. "ROYAL BAY DENTAL CO.", "GENERAL DENTISTRY", "INVISALIGN") run down the right edge of each section as a decorative motif. Sticky two-row header. Page height ~9,244px at 1440px viewport.',
  '',
  '---',
  '',
  '## Design Tokens (observed)',
  '',
  '### Colors',
  '- Background primary: #f5f0eb (warm greige/taupe)',
  '- Background secondary: #e8e0d8 (darker taupe — alternate section panels, top bar)',
  '- Text primary: #2c2c2c (near-black charcoal)',
  '- Text secondary: #6b6b6b (medium grey)',
  '- Accent/CTA gold: #c9a87c (warm gold — button borders, link arrows, star ratings)',
  '- CTA button style: white bg + #c9a87c 1px border + #c9a87c uppercase text (outlined, no fill default)',
  '- Phone CTA in nav: same outlined gold pill',
  '',
  '### Typography',
  '- Logo: Bold sans-serif all-caps "ROYAL BAY", thin horizontal rule, "DENTAL CO." below in tracked light weight',
  '- Headings (H1/H2): Serif — likely Cormorant Garamond or Playfair Display — mixed case, elegant',
  '- Body: Humanist sans-serif — likely Lato or Raleway — ~16px, light weight, comfortable line-height',
  '- Nav links: Spaced uppercase sans-serif, ~13-14px, letter-spacing ~0.08-0.1em',
  '- Vertical rotated labels: Uppercase, very spaced, featherweight — decorative only',
  '',
  '### Spacing',
  '- Section vertical padding: ~80-120px',
  '- Content max-width: ~1100-1200px centered',
  '- Grid gutters: ~30-40px',
  '',
  '---',
  '',
  '## Page Structure (top to bottom)',
  '',
  '1. **Top utility bar** — taupe bg, Instagram icon left, address + city right, "BOOK ONLINE HERE" outlined button far right',
  '2. **Main nav row** — white bg, "ROYAL BAY / DENTAL CO." logo left, dropdown nav links center-right (GENERAL DENTISTRY, INVISALIGN, COSMETIC DENTISTRY, ABOUT, CONTACT), phone CTA outlined gold pill far right',
  '3. **Hero** — full-bleed dark lifestyle photo (warm tones, interior/person), serif headline "GENERAL AND COSMETIC DENTISTRY", subhead "Your Local Dentist in Victoria, BC", italic "Cutting-edge dentistry meets...", 5-star rating with count, "BOOK ONLINE HERE" gold outlined CTA, scroll-down chevron arrow',
  '4. **Urgent help strip** — thin taupe bar, "GET URGENT HELP →" inline link, centered',
  '5. **About intro** — two-column: large portrait photo left (smiling woman, beach bg), "Creating Beautiful Smiles Together" serif heading right + 3-line paragraph about being part of the Royal Bay community; vertical "ROYAL BAY DENTAL CO." label on far right edge',
  '6. **Mission/values panel** — full-width taupe bg, centered: "Transforming Your Dental Experience" heading, long body paragraph about personalized care, "Learn more →" link with arrow',
  '7. **General Dentistry feature** — "SERVICES" italic eyebrow, "Comprehensive General Dentistry" heading, body copy, "Continue reading →"; large photo occupies right half; vertical "GENERAL DENTISTRY" label',
  '8. **General Dentistry sub-tiles** — 4 horizontal image+label tiles (SEDATION, DENTAL EMERGENCIES, DENTISTRY, DENTAL IMPLANTS) above heading "Premier Dental Care Tailored To Your Needs" + italic subline + "General dentistry →" CTA',
  '9. **New Patients welcome** — taupe panel: "ROYAL BAY DENTAL CO." eyebrow, "ALWAYS WELCOMING NEW PATIENTS" heading, body paragraph, "Contact us →" CTA; large lifestyle photos of diverse patients below',
  '10. **Invisalign section** — large photo left, "ROYAL BAY DENTAL CO." eyebrow right, "INVISALIGN" heading, short body, "Continue reading →"; vertical "INVISALIGN" label',
  '11. **Cosmetic Dentistry feature** — "SERVICES" eyebrow, "Transformative Cosmetic Dentistry" heading, body, "Continue reading →"; large photo right; vertical "COSMETIC DENTISTRY" / "DENTISTRY" label',
  '12. **Cosmetic sub-tiles + CTA panel** — "WORLD CLASS ORAL CARE" centered heading + subline + "Cosmetic dentistry →" CTA; then 4 image tiles (TEETH WHITENING, PORCELAIN VENEERS, COSMETIC BONDING, GUM CONTOURING)',
  '13. **Testimonials** — "ROYAL BAY DENTAL CO." eyebrow, "Patients Love IT HERE" heading, 5-star + "5.0 RATING FROM 325 REVIEWS"; 3-card carousel with quotation marks, patient review text, star rating, reviewer name; left/right arrow navigation',
  '14. **Contact Info section** — left: embedded Google Map centered on Victoria BC location; right: "GET IN TOUCH" eyebrow, "Contact Info" heading, subhead, address, phone, email, hours, Instagram icon',
  '15. **Footer** — taupe bg: "ROYAL BAY / DENTAL CO." logo left; nav links center (GENERAL DENTISTRY, COSMETIC DENTISTRY, INVISALIGN, CONTACT US); Instagram icon right; horizontal divider; "2026 Royal Bay Dental Co. | Sitemap | Privacy Policy" below',
  '',
  '---',
  '',
  '## Screenshot Inventory',
  '',
  '### Full-page captures',
  '- `desktop-full.png` — complete 1440x9244px page',
  '- `tablet-full.png` — complete page at 768px viewport width',
  '- `mobile-full.png` — complete page at 375px viewport width',
  '',
  '### Navigation',
  '- `nav-default.png` — full two-row header at scroll 0: top taupe utility bar + white main nav, 169px tall',
  '- `nav-scrolled.png` — header at 400px scroll (visually unchanged — both rows remain solid sticky)',
  '- `nav-hover.png` — second nav link in hover state',
  '',
  '### Hero',
  '- `desktop-hero.png` — first viewport: dark photo bg, serif headline, star rating, gold CTA button',
  '',
  '### Sections (desktop, per .x-section block)',
  '- `section-0-x-section.png` — hero with photo background and CTA',
  '- `section-1-x-section.png` — urgent help strip + about intro split layout',
  '- `section-2-section-two.png` — mission "Transforming Your Dental Experience" panel (top half)',
  '- `section-2-section-two-cont.png` — mission panel continued into General Dentistry intro',
  '- `section-3-x-section.png` — General Dentistry 4-service tile grid + "Premier Dental Care" headline',
  '- `section-4-x-section.png` — "ALWAYS WELCOMING NEW PATIENTS" taupe panel + patient photos',
  '- `section-5-x-section.png` — Invisalign section (photo left, text right)',
  '- `section-6-x-section.png` — Cosmetic Dentistry feature block',
  '- `section-7-x-section.png` — "WORLD CLASS ORAL CARE" + 4 cosmetic service tiles',
  '- `section-8-x-section.png` — "Patients Love IT HERE" testimonials with 3 review cards',
  '- `section-9-x-section.png` — Contact Info with embedded Google Map',
  '- `section-10-x-section.png` — lower contact/map area',
  '- `section-11-x-section.png` — footer-adjacent content block',
  '- `section-12-x-section.png` — footer region',
  '- `section-footer.png` — footer: logo, nav links, copyright on taupe bg',
  '',
  '### Scroll chunks (900px viewport sequential)',
  '- `scroll-chunk-00.png` — hero full viewport with CTA',
  '- `scroll-chunk-01.png` — urgent help bar + "Creating Beautiful Smiles Together" about intro',
  '- `scroll-chunk-02.png` — about intro bottom + "Transforming Your Dental Experience" taupe panel',
  '- `scroll-chunk-03.png` — mission text end + General Dentistry intro paragraph',
  '- `scroll-chunk-04.png` — 4-tile service grid (SEDATION / EMERGENCIES / DENTISTRY / IMPLANTS) + "Premier Dental Care" CTA',
  '- `scroll-chunk-05.png` — "ALWAYS WELCOMING NEW PATIENTS" full panel + diverse patient photos',
  '- `scroll-chunk-06.png` — Invisalign section top + Cosmetic Dentistry intro',
  '- `scroll-chunk-07.png` — Cosmetic Dentistry photo + "WORLD CLASS ORAL CARE" heading',
  '- `scroll-chunk-08.png` — 4 cosmetic tiles + "Patients Love IT HERE" testimonial cards',
  '- `scroll-chunk-09.png` — Contact Info: Google Map embed + address/phone/hours panel',
  '- `scroll-chunk-10.png` — contact bottom + full footer',
  '',
  '### Components',
  '- `component-button-primary.png` — "BOOK ONLINE HERE": white bg, #c9a87c 1px border, #c9a87c uppercase text, ~18px H padding, ~12px V padding, no background fill',
  '- `component-button-hover.png` — same button in hover state',
  '- `mobile-menu-open.png` — full-screen taupe overlay drawer: stacked uppercase items with chevrons (GENERAL DENTISTRY, INVISALIGN, COSMETIC DENTISTRY, ABOUT, CONTACT), phone, email, BOOK NOW; X close button top-right',
  '',
  '---',
  '',
  '## Animations Observed',
  '',
  '- **Hero entrance**: Headline and CTA fade up ~600ms ease-out on load (Cornerstone entrance animation)',
  '- **Vertical section labels**: Static CSS decoration using writing-mode: vertical-rl — no animation',
  '- **Header on scroll**: Both rows stay solid/sticky with no size or color change detected',
  '- **CTA buttons (outlined)**: Hover fills background to #c9a87c, text flips to white; ~200ms ease transition',
  '- **Phone/nav CTA pill**: Same fill-on-hover as primary CTA',
  '- **Arrow links ("Continue reading →")**: Arrow nudges 4px right on hover; ~200ms ease',
  '- **Service image tiles**: Likely subtle scale(1.02) or translateY(-3px) + shadow on hover; ~200ms ease',
  '- **Testimonial carousel**: Horizontal translate transition on arrow click, ~300ms ease',
  '- **Mobile menu**: Full-screen overlay fades or slides in from right, ~300ms; nav items may stagger-fade',
  '- **Scroll-triggered content**: Sections likely fade-in from slight Y offset as they enter viewport (Cornerstone default); ~400-600ms per element',
  '',
  '---',
  '',
  '## Key Content Details',
  '',
  '- Practice: Royal Bay Dental Co.',
  '- Location: 345B Latoria Blvd #202, Victoria, BC, V9C 0S9',
  '- Phone: (778) 653-9426',
  '- Email: info@royalbaydentalco.ca',
  '- Hours: Mon-Thu 8:30am-5:30pm | Fri 8:30am-3pm | Sat-Sun Closed',
  '- Social: Instagram only (no Facebook/Twitter visible)',
  '- Rating: 5.0 stars from 325 Google reviews',
  '- Nav has 5 top-level items: General Dentistry (dropdown), Invisalign (dropdown), Cosmetic Dentistry (dropdown), About (dropdown), Contact (flat)',
  '- Services: General Dentistry, Sedation, Dental Emergencies, Dental Implants, Invisalign, Cosmetic Dentistry, Teeth Whitening, Porcelain Veneers, Cosmetic Bonding, Gum Contouring',
  '- No blog, no photo gallery section on homepage',
  '- Accessibility: third-party accessiBe widget (blue circle icon, fixed bottom-left)',
  '- Copyright year: 2026',
];

fs.writeFileSync(p, lines.join('\n'), 'utf8');
console.log('Written context.md (' + lines.length + ' lines)');
